### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by CamilaAtehortua** [CamilaAtehortua/Equipo3_se_ppi2020#8]

**Comment by marthaduque** [comment]
Falta definir la visión de acuerdo a lo indicado en el documento de la semana 2 de IR y en caracteristicas deben quedar :  las funcionalidades del aplicativo tales como que las personas interesadas se puedan matricular a dichos eventos y los responsables de los eventos pueden consultar a un evento especifico que personas se han matriculado .
